# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
remote_theme             : BlackrockDigital/startbootstrap-clean-blog-jekyll

# Site Settings
title                    : "@jeffsidea"
email                    : "jschnurr@gmail.com"
author                   : "Jeff Schnurr"
description              : "Musings on technology and innovation."
url                      : "https://jeffsidea.com" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "jschnurr/jeffsidea.com" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
github_username          : "jschnurr"
linkedin_username        : "schnurr"
twitter_username         : "jeffsidea"

# Build settings
markdown:          kramdown
highlighter: rouge
paginate:          5
paginate_path:     "/posts/page:num/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  # - jekyll-mentions
  # plugins below are defaults with github anyway, so use them locally too
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

jekyll-mentions:
  base_url: https://twitter.com
