# Site settings
title: "@jeffsidea"
description: "Musings on technology and innovation."
url: "https://jeffsidea.com"
baseurl: ''

google_analytics: 'UA-19292326-1'
disqus_shortname: 'jeffsidea'

# remote_theme: joshgerdes/jekyll-uno
remote_theme: matthiaslischka/jekyll-uno

author:
  name: 'Jeff Schnurr'
  email: jschnurr@gmail.com
  twitter_username: jeffsidea
  github_username:  jschnurr
  linkedin_username:  schnurr

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-include-cache

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', '.travis.yml', 'vendor', 'docker-compose.yml', 'CNAME']